"""empty message

Revision ID: f498491ff1d6
Revises: 1a6cb90b6fe3
Create Date: 2024-05-09 20:31:13.067779

"""
# add one more response table in
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f498491ff1d6'
down_revision = '1a6cb90b6fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('response_content', sa.String(length=1000), nullable=True),
    sa.Column('date_responded', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request.request_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    # ### end Alembic commands ###
