"""empty message

Revision ID: f7d4c2d35a04
Revises: f498491ff1d6
Create Date: 2024-05-12 16:58:58.921518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d4c2d35a04'
down_revision = 'f498491ff1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_user')
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
    #     batch_op.drop_column('password')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('password', sa.VARCHAR(length=60), nullable=False))
    #     batch_op.drop_column('password_hash')

    # op.create_table('_alembic_tmp_user',
    # sa.Column('user_id', sa.INTEGER(), nullable=False),
    # sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    # sa.Column('user_name', sa.VARCHAR(length=100), nullable=False),
    # sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    # sa.PrimaryKeyConstraint('user_id'),
    # sa.UniqueConstraint('email')
    # )
    pass
    # ### end Alembic commands ###
